### ISSUE TITLE
feat: Update to be used in new FE stack

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/generator-compost#5]
Do we want to reactivate and update this to be used with the new FE stack?

I am working on a new project and every time I have to create a folder, create yaml, css, js and twig file I want to have this back :)

My suggestion would be to simplify it a little bit:
Steps:
- What type of component is it (1 - element, 2 - component, 3 - template-components, 4 - template): [1-4]
- What is the name of the new component? [A-Z]
- What do you need? [css, twig, yaml, js] (<- maybe this can be multiple choice select?)

That's it. As templates we could use the `ExampleCard` markup. Thoughts?

**Comment by mlnmln** [comment]
@krisimmig 

Yes, should be fairly easy. 

> What type of component is it (1 - element, 2 - component, 3 - template-components, 4 - template): [1-4]

I would not at add the "type" of component to the scaffolder. It creates a tight coupling to a specific structure. I think it is ok to expect people to cd into the directory where they want scaffold st. 

Rest seems alright, and most feature are already in this packages. 

We just need to update the templates. 

> That's it. As templates we could use the ExampleCard markup. Thoughts?

Good idea for structure, but we must not scaffold any potential example dead code. 

Everything where people need to make manual changed / delete stuff must be avoided. 

Will work on that.

**Comment by krisimmig** [comment]
@mlnmln looks good, works well.

Some points I noticed:
- template only lets you choose twig, maybe we make it default and don't even give the option to choose it
- why do we need to add the package.json file? Can we make it optional?

**Comment by mlnmln** [comment]
> @mlnmln looks good, works well.

> template only lets you choose twig, maybe we make it default and don't even give the option to choose it

yes makes sense, wanted to get some out quickly so the multiple options was kept in from the original code. going forward i think this should have as little choices as possible. 

> why do we need to add the package.json file? Can we make it optional?

We need it, if we were to create reusable patterns and publish them on a registry. I'll remove it for now. 

Going forward I think it makes sense to treat all patterns as local packages, which would make extracting them later a lot easier. Will postpone.

**Comment by krisimmig** [comment]
@mlnmln I just noticed while using this version that no yaml file is created, is that on purpose?
I would suggest to create an empty yaml file when the user wants to have one, right?

**Comment by mlnmln** [comment]
yes should be added. Used to be JSON files that were created. will add YAML files

**Comment by mlnmln** [comment]
Did another batch of updates and created a new release. 

This seems good enough for now, closing. 

Open remaining ideas / features in new issues please.
